vnstat: run as vnstat user/group
Run vnstatd as specific user instead of root.  Can no longer stomp on
any directories/files it feels like.  This may help prevent losing data
if vnstat is using custom data directory residing on an as yet unmounted
fs.

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

diff --git a/net/vnstat/files/vnstat.init b/net/vnstat/files/vnstat.init
--- a/net/vnstat/files/vnstat.init
+++ b/net/vnstat/files/vnstat.init
@@ -1,13 +1,21 @@
 #!/bin/sh /etc/rc.common
 # Copyright (C) 2008-2011 OpenWrt.org
 
-START=99
+START=95
+USE_PROCD=1
+
+CONFIGFILE="/etc/vnstat.conf"
 
 USE_PROCD=1
 
 vnstat_option() {
 	sed -ne "s/^[[:space:]]*$1[[:space:]]*['\"]\([^'\"]*\)['\"].*/\1/p" \
-		/etc/vnstat.conf
+		${CONFIGFILE}
+}
+
+service_triggers()
+{
+        procd_add_reload_trigger "vnstat"
 }
 
 start_service() {
@@ -18,7 +26,7 @@ start_service() {
 		exit 1
 	}
 
-	mkdir -p "$lib"
+#	mkdir -p "$lib"
 
 	init_ifaces() {
 		local cfg="$1"
@@ -61,8 +69,11 @@ start_service() {
 		config_get lnk "$cfg" symlink
 		config_get backup_dir "$cfg" backup_dir
 		config_list_foreach "$cfg" interface init_iface
+	}
 
-		return 1
+	chown -h vnstat:vnstat ${CONFIGFILE} || {
+		logger -s -t vnstat -p daemon.err "Invalid UID/GID. Aborting startup"
+		exit 1
 	}
 
 	config_load vnstat
@@ -71,8 +82,9 @@ start_service() {
 	procd_open_instance
 	procd_set_param stdout 1
 	procd_set_param stderr 1
+	procd_set_param user vnstat
 	procd_set_param command /usr/sbin/vnstatd --nodaemon
-	procd_set_param file /etc/vnstat.conf
+	procd_set_param file "${CONFIGFILE}"
 	procd_set_param respawn
 	procd_close_instance
 }
